version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: Asdfghjkl
      POSTGRES_USER: thecoddiwompler
      POSTGRES_DB: employee
    ports:
      - "5432:5432"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: model-db-postgres:latest
    depends_on:
      - postgres